### ISSUE TITLE
Why are there 2 App Specification .yaml files?

### ISSUE THREAD

**Issue by klausbadelt** [digitalocean/sample-dockerfile#7]
There is `app.yaml` and `deploy.template.yaml`, with the latter seemingly not following your [App Specification Reference](https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/). Could you explain or, better, document this somewhere?

**Comment by klausbadelt** [comment]
Also, the location `.do/` made me assume (by convention of `.circleci.yml`, `.travis.yml`, `.github/` etc.) that the file configures the deploy - but that doesn't seem to be the case (the `doctl` CLI is needed to manually push the config). Is this correct? If so, I find the location (combined with lack of documentation) confusing in this example... Happy to stand corrected though :-)

**Comment by bojand** [comment]
Hello, :wave:. The `.do` directory contains files for working with the DigitalOcean App Platform. `app.yaml` is the app spec for this repository. It serves as a reference, and it can be used to create and update the app manually via `doctl` once a user has forked the repository. You are correct, the app spec has to be explicitly specified in `doctl` to perform operations with the app, and it's not automatically picked up by the CLI or the GitHub integration in the dashbaord. We may revisit this in the future, and if we do we'll document it; but the explicit intentional use of the app spec with `doctl` prevents users from accidentally or unintentionally making changes to their apps. 

Note that the app can be deployed automatically using the DigitalOcean App dashboard ([as documented](https://www.digitalocean.com/docs/app-platform/how-to/create-apps/)) and it would work fine without `.do/app.yaml` or any app specification file in the repository. Of course app specification file can be used to additionally customize the app and build or run time behavior, but it can only be used with `doctl` or DigitalOcean API.

The `deploy.template.yaml` file is actually what powers the ["Deploy to DigitalOcean" button](https://www.digitalocean.com/docs/app-platform/how-to/add-deploy-do-button/), and it has to be in `.do/` directory. The format for that file is very similar, but slightly different than the app spec. Essentially it's just the app specification nested in a `spec` property.

Hope this clears it up! We'll try to improve documentation around these details. There are additional [tutorials](https://www.digitalocean.com/community/tutorials?q=+%5BDigitalOcean+App+Platform%5D) and [questions](https://www.digitalocean.com/community/questions?q=+%5BDigitalOcean+App+Platform%5D) in our Community site. Feel free to play around and ask any other questions. Happy hacking!
